#!/usr/bin/bash

# This script updates all the packages installed.

sudo dnf upgrade --refresh -y
sudo flatpak update -y

# Update snaps if snapd is installed.
if [ -f "/usr/bin/snap" ]; then
sudo snap refresh
fi

sudo dnf remove -y podman-gvproxy unbound-anchor
sudo dnf autoremove -y