#!/usr/bin/bash

# The script I run to install the apps I need for a development
# environment virtual machine desktop.

# Install rpm packages.
sudo dnf install -y gnome-extensions-app \
gnome-tweaks neofetch gnome-shell-extension-user-theme \
java-latest-openjdk-devel nodejs npm dotnet-sdk-6.0 \
python3-pip python-unversioned-command gcc clang \
cmake mingw*-gcc mingw*-gcc-c++ \
grpc-devel mingw*-protobuf-static mingw*-protobuf-tools \
community-mysql-devel community-mysql libXxf86vm-devel \
vulkan-tools vulkan-loader-devel vulkan-validation-layers-devel \
mingw*-vulkan-validation-layers mingw*-vulkan-tools \
mingw*-vulkan-loader mingw*-vulkan-headers \
glew-devel mingw*-glew-static mingw*-glew-tools \
glslc glfw-devel glm-devel stb_image-devel wine \
mingw*-winpthreads-static

# Installing VS Code
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
dnf check-update
sudo dnf install -y code

# Install snapd.
sudo dnf install -y snapd
sudo ln -s /var/lib/snapd/snap /snap

# Install snaps.
sudo snap install intellij-idea-community --classic
sudo snap install gradle --classic
sudo snap install android-studio --classic

# Remove weak dependencies.
sudo dnf remove -y ImageMagick caca-utils compiler-rt libomp \
libomp-devel nodejs-docs nodejs-full-i18n w3m-img xdpyinfo \
xprop xrandr xwininfo dosbox-staging \
openssl-pkcs11 sane-backends-drivers-cameras \
sane-backends-drivers-scanners

# Autoremove all other unnecessary packages.
sudo dnf autoremove -y
